### ISSUE TITLE
For your account security, logging into Facebook from an embedded browser is disabled.

### ISSUE THREAD

**Issue by CharlieZheng** [facebook/facebook-android-sdk#1023]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Java version

1.8

### Android version

API 30

### Android SDK version

12.0.0

### Installation platform & version

Gradle

### Package

Login

### Goals

User can login with Facebook, even if his device doesn't install Facebook app and chrome.

### Expected results

when I invoke Facebook login api, if the device didn't have chrome install, toast instead of showing error message in browser.

### Actual results

showing error message in browser.
<img src="http://49.234.30.187:8012/IMG_1756.jpeg" width="40%">

### Code samples & details

```java
// INSERT YOUR CODE HERE
CallbackManager callbackManager = CallbackManager.Factory.create();
LoginManager.getInstance().registerCallback(callbackManager, callback);
LoginManager.getInstance().logInWithReadPermissions((Activity) context, Arrays.asList("public_profile"));
```

**Comment by linmx0130** [comment]
Hi @CharlieZheng, thanks for raising this issue. However, this is a security feature, not a bug. Due to the security reason, we have disabled the login without Facebook App or CustomTab.

Please refer to https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews for more information.

**Comment by Shimingli** [comment]
can u help me @linmx0130  ，because my company tablet is very old，can not support download facebook App。
so  I need u ，come on bady，u are good man

**Comment by ibrahim-musa** [comment]
@linmx0130 Hi Lin, this issue also happened to some of my user of my app. They already had Facebook app installed and already in a logged in state. But when calling this code below
```
final LoginManager loginManager = LoginManager.getInstance();
loginManager.registerCallback(getCallbackManager(), new LoginManagerCallback(promise));
Activity activity = getCurrentActivity();
if (activity != null) {
      loginManager.logIn(activity,
            Utility.reactArrayToStringList(permissions));
}
```
it open a Facebook app in a logged out state. And when the user try to enter email and password to log in, it show **_For your account security, logging into Facebook from an embedded browser is disabled_**. (_see video below for more detailed picture_)

From the video that user sent to me (attached below) it's also look like it open a Facebook app instead of Chrome custom tab (it didn't show X button on top left) or a webview (it didn't show as a dialog). Why the app still think it logged in an embedded browser?

Here's my configuration
Facebook SDK v14.1.1
Android SDK version 30
Java version 1.8

Device affected: Samsung Galaxy Note 20 Ultra (Android 12) with Facebook app version 389.0.0.42.111 installed.


https://user-images.githubusercontent.com/47311555/197849580-18c1b9b6-dd98-4e98-beda-f28c3a71faf8.mp4
