### ISSUE TITLE
Found resources with the same name 'com_facebook_device_auth_instructions' within the same variant '--dependency--' for the same language 'es-rES'

### ISSUE THREAD

**Issue by TandohAnthonyNwiAckah** [facebook/facebook-android-sdk#1033]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Java version

1.8

### Android version

Android 11

### Android SDK version

12.2.0

### Installation platform & version

Gradle

### Package

Login

### Goals

I want to implement facebook login authentication in my project.

### Expected results

Facebook login should work without any build error

### Actual results

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stringDebugResourceLocator'.
> Found resources with the same name 'com_facebook_device_auth_instructions' within the same variant '--dependency--' for the same language 'es-rES'. Resource names must be unique within a singlevariant-language environment

Using  `implementation 'com.facebook.android:facebook-android-sdk:12.2.0'`

### Code samples & details

```java
implementation 'com.facebook.android:facebook-android-sdk:12.2.0'

When i comment out the above my project works fine. Issue is coming from the above.
```

**Comment by linmx0130** [comment]
Hi @TandohAnthonyNwiAckah! Thanks for raising this issue. It seems that you're importing more than one Facebook Android SDK versions/distributions, which results in a name conflict on `com_facebook_device_auth_instructions`. Could you check other kits that you are importing? They may have a dependency on the old versions of Facebook Android SDK.

It would be great if you can share the gradle configuration with us so that we can find the root cause. If that's not possible, you can have a try to find which kit other than Facebook Android SDK also contains `com_facebook_device_auth_instructions`.

**Comment by TandohAnthonyNwiAckah** [comment]
These are the two main unique dependencies i am using @linmx0130 .

```
 implementation 'com.facebook.android:facebook-android-sdk:12.2.0'
 implementation 'com.facebook.android:audience-network-sdk:6.1.0'
```




![Screen Shot 2022-01-05 at 10 14 33 AM](https://user-images.githubusercontent.com/29551282/148200995-fb50c7ee-b530-4d62-8dc1-10c75aa69269.png)

**com_facebook_device_auth_instructions is contain in both  es.xml and es-rES.xml**

**Comment by linmx0130** [comment]
@TandohAnthonyNwiAckah Did you set the product flavor? How did you set the configure for resources?

**Comment by TandohAnthonyNwiAckah** [comment]
Yes i did @linmx0130 .

```
  release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.key
        }

        debug {

            signingConfig signingConfigs.key

        }
```

**Comment by linmx0130** [comment]
`com_facebook_device_auth_instructions` appears in both `es.xml` and `es-rES.xml` should be fine because they're for different regions.

I guess you may specify the language support by following https://developer.android.com/guide/topics/resources/multilingual-support#specify-the-languages-your-app-supports but I'm not quite sure.

Since I cannot reproduce the problem, could you share me with a minimal reproducible example for us to find the problem?

**Comment by TandohAnthonyNwiAckah** [comment]
I have commented it out for the mean time. WIll look at it again and get in touch . Thanks very much @linmx0130

**Comment by TandohAnthonyNwiAckah** [comment]
Issue resolved after invalidate cache and upgrading all dependencies in my projects  .
