### ISSUE TITLE
Latest SDK Issue

### ISSUE THREAD

**Issue by ramkotu** [facebook/facebook-android-sdk#1035]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Java version

1.8

### Android version

30

### Android SDK version

12.0.2

### Installation platform & version

com.facebook.android:facebook-android-sdk:12.2.0

### Package

AppLinks

### Goals

I Updated the 4.0.8 version to 12.2.0  (com.facebook.android:facebook-android-sdk:12.2.0) our applinks AppLinks.getTargetUrlFromInboundIntent not woking and com.facebook.FacebookActivity and com.facebook.FacebookContentProvider it shows error in AndroidMainfest file

### Expected results

I Updated the 4.0.8 version to 12.2.0  (com.facebook.android:facebook-android-sdk:12.2.0) our applinks AppLinks.getTargetUrlFromInboundIntent not woking and com.facebook.FacebookActivity and com.facebook.FacebookContentProvider it shows error in AndroidMainfest file

### Actual results

I Updated the 4.0.8 version to 12.2.0  (com.facebook.android:facebook-android-sdk:12.2.0) our applinks AppLinks.getTargetUrlFromInboundIntent not woking and com.facebook.FacebookActivity and com.facebook.FacebookContentProvider it shows error in AndroidMainfest file

### Steps to reproduce

I Updated the 4.0.8 version to 12.2.0  (com.facebook.android:facebook-android-sdk:12.2.0) our applinks AppLinks.getTargetUrlFromInboundIntent not woking and com.facebook.FacebookActivity and com.facebook.FacebookContentProvider it shows error in AndroidMainfest file

### Code samples & details

```java
I Updated the 4.0.8 version to 12.2.0 (com.facebook.android:facebook-android-sdk:12.2.0) our applinks AppLinks.getTargetUrlFromInboundIntent not woking and com.facebook.FacebookActivity and com.facebook.FacebookContentProvider it shows error in AndroidMainfest file
```

**Comment by linmx0130** [comment]
Hi @ramkotu, thanks for raising this issue.

`AppLinks.getTargetUrlFromInboundIntent` is from [bolts library](https://github.com/BoltsFramework/Bolts-Android). You may need to import this library to use this method since Facebook Android SDK has removed it from our dependency list. However, this library is archived and no any new updates will be provided. We suggest you to remove its use case or follow https://github.com/BoltsFramework/Bolts-Android/blob/master/bolts-applinks/src/main/java/bolts/AppLinks.java#L78 to implement one if you do need this method.

Could you share the error in AndroidMainfest file in a new issue? And could you follow our latest [guidelines on integrating Facebook Android SDK](https://developers.facebook.com/docs/facebook-login/android) to upgrade? Thanks a lot!
