### ISSUE TITLE
HttpStatus: 400 - Unsupported get request. 

### ISSUE THREAD

**Issue by hoangduchuu** [facebook/facebook-android-sdk#572]
When I initialize faecbook SDK, I have a problem with the error logs bellow:
`E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '745820495856200' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}`

**Comment by xiehongxin** [comment]
How do you solve this problem?

**Comment by KylinChang** [comment]
Hi @xiehongxin , this issue may be caused by an invalid facebook app id, what's your facebook app id? If you don't want to expose your app id here, you can send it to my email kylinchang@fb.com.

**Comment by xiehongxin** [comment]
> Hi @xiehongxin , this issue may be caused by an invalid facebook app id, what's your facebook app id? If you don't want to expose your app id here, you can send it to my email [kylinchang@fb.com](mailto:kylinchang@fb.com).

Thank you, I try it first.

**Comment by adityainterwork** [comment]
did anyone found the solution of this problem?

**Comment by lowwailum123** [comment]
Still waiting for the solution

**Comment by matthew-reilly** [comment]
Seeing this as well.

**Comment by hassan963** [comment]
any solution yet?

**Comment by lowwailum123** [comment]
Based on my experience, this happens because you haven't log in to Facebook, you can ignore this error since it doesn't crash your main program. 
You just need to log in to Facebook using the Facebook login button given in their official documentation afterwards, then perform any necessary graph request you need.

**Comment by donelpasso** [comment]
> Based on my experience, this happens because you haven't log in to Facebook, you can ignore this error since it doesn't crash your main program.
> You just need to log in to Facebook using the Facebook login button given in their official documentation afterwards, then perform any necessary graph request you need.

What do you mean ignore it? The app isn't doing anything because of this error! Try doing it with another fb account instead of yours(developer)

**Comment by jaafarAB** [comment]
The question is. Does an app that still in development mode (Not reviewed yet) can access facebook graph Api resource?
I am working on an ionic angular app that supports facebook login and i am getting the same error.
But as @donelpasso said. My app isn't crashing and i can login normally.
Is it a problem related to permissions ?

**Comment by ChristianEGB** [comment]
@hoangduchuu At the end you closed this issue. Can we have a feedback of yours with how did you solve this?

**Comment by amanuel2** [comment]
How do you solve this? And why is this issue closed, without solving.

**Comment by ChristianEGB** [comment]
In my opinion this should be reopened, what do you guys think about to open a new issue about this? In some way Facebook does now recognize the app ID and there is no part in the Facebook documentation where this is mentioned or maybe that the app in some way have to be registered in some other part or maybe that the company have to be validated in some way.

**Comment by amanuel2** [comment]
I Agree @ChristianEGB link me to the new issue please :)

**Comment by Andre-max** [comment]
> Based on my experience, this happens because you haven't log in to Facebook, you can ignore this error since it doesn't crash your main program.
> You just need to log in to Facebook using the Facebook login button given in their official documentation afterwards, then perform any necessary graph request you need.

I'm developing an Android app that uses Facebook login and I'm getting the same error. However, the user can still sign in and I'm experiencing no crash. I've counter-checked my Facebook app id with the one in my strings resources and they are the same. So I also suggest that a new issue be opened to get a solution to this error.

**Comment by amanuel2** [comment]
@Andre-max Users can sign up in mine. And using basically the same code to log in for some reason doesnt work.

**Comment by Andre-max** [comment]
> @Andre-max Users can sign up in mine. And using basically the same code to log in for some reason doesnt work.

Apparently, I made a mistake in my comment. In actual sense, users can sign up successfully but I haven't yet implemented sign in. 
Hopefully login works with the same code, if it doesn't, I hope there will be a solution by then.

**Comment by Artuom193** [comment]
Facebook SDK 7.21.2, same problem

**Comment by ChristianEGB** [comment]
Give me the opportunity to replicate  again the issue, I will create a new one and I will tag everyone.

**Comment by Artuom193** [comment]
Unity version: **2019.3.0f5**
Facebook SDK version: **7.21.2**

In fact, I have a much more serious problem than this. But I think that this error is its root.

My code:
![image](https://user-images.githubusercontent.com/52217614/92286196-007d9700-ef0f-11ea-96b6-bbc8aba86405.png)

Error: 
![image](https://user-images.githubusercontent.com/52217614/92286423-ab8e5080-ef0f-11ea-9953-30dc2798962d.png)

**Comment by Artuom193** [comment]
@ChristianEGB In the case of Unity3D, the ID is set only in the AndroidManifest itself
![image](https://user-images.githubusercontent.com/52217614/92290424-b00d3600-ef1c-11ea-91dc-a1d0398064ee.png)

**Comment by Dandash1999** [comment]
+1

**Comment by amanuel2** [comment]
For me, the Android SDK is the problem. Same exact code for registering users' work but doesn't work for login. For both methods, I just use the Facebook Android SDK to pull the same amount of user information. My working register code : https://github.com/Servo-Team/Servo/blob/master/app/src/main/java/com/servo/auth/Register.java#L248

**Comment by janatar20** [comment]
[gatsby-remark-embedder-master.zip](https://github.com/facebook/facebook-android-sdk/files/5212097/gatsby-remark-embedder-master.zip)

**Comment by persicoandroid** [comment]
The same as documentation eh..... hehehe

**Comment by persicoandroid** [comment]
Solved adding: tools:replace="android:value"

`<meta-data
            android:name="com.facebook.sdk.ApplicationId"
            tools:replace="android:value"
            android:value="@string/facebook_app_id"`

**Comment by Artjoms-Sc** [comment]
Also faced this issue and still don't found a solution.

If you check this issue author's AppId like this [https://graph.facebook.com/v5.0/745820495856200/](https://graph.facebook.com/v5.0/745820495856200/) u can see that it works fine. Soo @hoangduchuu, please add some comments how you managed this error to be solved

**Comment by kernokus** [comment]
i have the same problem

**Comment by edwinMj13** [comment]
i dont have, facebook access in my app. but this still shows up in every testing app's log ,why is that

**Comment by giriteja94495** [comment]
My app id is proper.                                                                                                                                                                             
 Still the same problem, Can Someone tell how to resolve that issue or why don't they open the issue again

**Comment by Smile-Cats** [comment]
i have the same problem, Can Someone tell how to resolve that issue or why don't they open the issue again

**Comment by GoldenSoju** [comment]
I get the same error code every time I start my app.
In around 30% of the cases, it seems like this error leads to a stop of my app.
At least that is what I think, as in those cases, this error is the last log-event I get before the app freezes.
I cannot be 100% sure if that is really the reason the app freezes though.
The app is still in internal testing stage, so maybe the error occurs because the app wasn't reviewed by facebook yet?

**Comment by AmirDiafi** [comment]
+1

**Comment by FaizanAhmad127** [comment]
+1

**Comment by nhatphongcgp** [comment]
+2

**Comment by tfrysinger** [comment]
I am seeing the exact same error on startup. I have a test app that reproduces it. My "real" app (which uses the app registered with FB and which this test app is accessing) has gone through review and been approved, but I am still seeing this in both the real app, and this test app which attempts to get the same FB credentials. 

So whoever posted above the idea that the problem is that your FB app hasn't been approved yet - that isn't the problem.

I am using the Login Button API, and including the app ID in metadata within the manifest per the docs. I am able to start the test app - I see this error, but my app continues and allows the user to tap the login button to log in, which it does successfully. So for me I guess it is a "benign error", but I think it should not be happening.

Btw - you will notice below the test app is "InstagramTest". This is because my main problem is how to authenticate a user to be able to pull their Instagram photos/videos. I was told at the recent F8 by a developer I should be able to use a FB token to pull the Instagram content, as long as the two are connected. Wrong. Doesn't work. If anyone has been able to validate an Instagram login via Android without having to resort to WebView, I'd LOVE to talk to you!

Android Studio 4.2.2
login:  implementation 'com.facebook.android:facebook-login:11.1.1'

Manifest:
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.android.instagramtest">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:name=".InstagramTest"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.InstagramTest">
        <activity android:name=".FBLoginActivity">
            
        </activity>
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />
        <meta-data
            android:name="com.facebook.sdk.ClientToken"
            android:value="@string/facebook_client_token"/>
    </application>

</manifest>

**Comment by Cxb168** [comment]
+1
