### ISSUE TITLE
LoginManager.logOut() not working

### ISSUE THREAD

**Issue by sabafromwandio** [facebook/facebook-android-sdk#580]
I use default login manager like `LoginManager.getInstance()`, then login and logout , but when i check token after logout like this `AccessToken.getCurrentAccessToken()`  it still exists

**Comment by Rasalexman** [comment]
I heve the same issue

**Comment by KylinChang** [comment]
Hi @sabafromwandio , @Rasalexman , which version of SDK are you using? I cannot reproduce the issue, it would be better if you can share example code.

**Comment by thanakitskp** [comment]
I use default login manager like LoginManager.getInstance(), then login and logout , but when i check token after logout like this AccessToken.getCurrentAccessToken() it still exists

**Comment by KylinChang** [comment]
Hi @thanakitskp , do you use the latest version of SDK?

**Comment by babkouew** [comment]
I have the same issue both on Android and iOS I use the latest sdK 5.8.0 in iOS and 5.9.0 in Android.  LoginManager.getInstance() does not work. This issue has been lingering for a time now and the ticket posted in facebook-iOS-sdk github has even been archived without any hints on how to solve the problem. They however said that this was due to cookies in browsers that save token authentication data that gets automatically reused each time the user wants to login with facebook.

**Comment by ranjandas503** [comment]
I am also getting the same issue, have anyone got any solution for that.
I have used version 5.5.1 and 5.12.0 and getting the same issue.

**Comment by shahzadafridi** [comment]
If someone is still facing issue then there is a solution which worked for me.

`          if (AccessToken.getCurrentAccessToken() != null) {
                GraphRequest(
                    AccessToken.getCurrentAccessToken(), "/me/permissions/", null, HttpMethod.DELETE,
                    GraphRequest.Callback {
                        AccessToken.setCurrentAccessToken(null)
                        LoginManager.getInstance().logOut()
                    }
                ).executeAsync()
            }
`
